name: 报告安全漏洞
description: 向我们报告代码安全漏洞和隐私泄漏等敏感信息，促进项目的安全性和可靠性
title: "<安全漏洞>:"
labels: [安全问题]
body:
- type: markdown
  attributes:
    value: |
      ## GitCode 安全漏洞报告指引

      GitCode 安全漏洞报告功能允许用户能够快速、安全地报告代码安全漏洞和隐私泄漏等敏感信息，以促进项目的安全性和可靠性。它涵盖了多个方面，包括代码漏洞、依赖关系漏洞、安全警报等：

      - **漏洞报告**：漏洞报告指的是在代码中发现的潜在安全问题或漏洞。这些漏洞可能导致系统受到攻击或遭受损害，例如 SQL 注入、跨站脚本 (XSS)、路径遍历等
      - **依赖漏洞**：项目所依赖的外部库或软件包中存在的安全问题，避免攻击者可以利用依赖漏洞来执行恶意代码
      - **安全警报**：代码中存在的安全风险，例如编码错误、设计缺陷或未经授权的访问等原因而产生的安全风险等

- type: input
  attributes:
    label: CVE 编号
    placeholder: |
      eg. CVE-2024-####
    description: |
      若有漏洞的`CVE`编号，请提供；若不清楚或尚未知晓，请忽略

  validations:
    required: false
  render: markdown

- type: textarea
  attributes:
    label: 影响程度
    placeholder: |
      这是什么类型的漏洞？谁会受到影响？
      
    description: |
      安全漏洞的影响程度通常取决于漏洞的类型和攻击向量。例如，如果漏洞是跨站脚本（XSS），受影响的用户可能包括访问受感染页面的所有用户。对于其他类型的漏洞，例如身份验证绕过或权限提升，影响范围可能更加有限，但仍然会对系统的安全性产生重大影响

  validations:
    required: false

- type: textarea
  attributes:
    label: 补丁
    placeholder: |
      问题是否已修补？应升级到哪些版本？
      
    description: |
      如果安全漏洞已经得到修补，相关的补丁信息应当提供给用户。这可能包括指导项目成员升级到包含修复程序的特定软件版本。通常，最新版本包含了最新的安全修复。

  validations:
    required: false

- type: textarea
  attributes:
    label: 解决方法
    placeholder: |
     是否有办法在不升级的情况下修复或纠正漏洞？
      
    description: |
      即使没有可用的补丁，项目成员仍然可以通过执行一些临时措施来减轻安全漏洞的风险。这些临时措施通常称为“解决方法”或“临时修复”。这些方法可能包括配置系统设置、禁用受影响的功能或模块，或者实施其他安全控制来限制漏洞的利用。

  validations:
    required: false

- type: textarea
  attributes:
    label: 参考资料
    placeholder: |
      可以访问哪些链接以获取更多信息？
      
    description: |
      为了帮助我们深入了解漏洞以及相关的修复和解决方法，请提供更多参考资料。这些资料可能包括安全漏洞报告、官方补丁说明、安全建议或其他相关文档的链接。项目成员可以通过查阅这些参考资料来获取更多关于漏洞和其影响的详细信息，以及如何采取适当的措施来保护系统。

  validations:
    required: false

- type: textarea
  attributes:
    label: 常见弱点枚举（CWE）
    placeholder: |
      请输入常见弱点枚举（CWE）编号或关键词
      
    description: |
      CWE 中的弱点可以涵盖各种安全问题，例如缓冲区溢出、跨站脚本（XSS）、SQL 注入等。通过了解和识别软件中可能存在的弱点，开发人员可以采取相应的措施来提高系统的安全性，例如加强输入验证、使用安全编码实践等。

  validations:
    required: false

- type: dropdown
  id: severity
  attributes:
    label: 严重程度
    description: |
      漏洞或安全问题对系统安全性的潜在影响程度。通常使用未知(Unknown)、低（Low）、中等（Moderate）、高（High）、严重（Critical）等不同的级别来表示漏洞的严重性
      
    options:
      - 未知(Unknown)
      - 低（Low）
      - 中等（Moderate）
      - 高（High）
      - 严重（Critical）
    default: 0
  validations:
    required: true

- type: input
  attributes:
    label: 报告人信息
    description: |
      请填写你的联系方式

  validations:
    required: false
